/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
//       assertEquals(2 , classUnderTest.roll(2).length);
//       assertTrue(classUnderTest.containsDuplicates(new int[]{2,2,3,4}));
    }
}
