/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.ArrayList;
import java.util.Collections;

public class Library {

    public static void main(String[] args) {

    }


    public int[] roll(int numRoll) {

        int[] tryArray = new int[numRoll];

        for (int i = 0; i < tryArray.length; i++) {
            tryArray[i] = (int) (5 * Math.random()) + 1;
        }
        return tryArray;
    }

    public boolean containsDuplicates(int[] inputArray) {
      boolean status = false;
        for (int i = 0; i < inputArray.length; i++) {
            for (int j = i+1; j < inputArray.length; j++) {
                if (inputArray[i] == inputArray[j]){
                    status = true;
                }
            }
        }
        return status;
    }

    public double average(int[] inputArray) {
        int sum = 0;
        for (int i = 0; i < inputArray.length; i++) {
            sum = sum + inputArray[i];
        }
        double avg = (double) sum / inputArray.length;
        return avg;
    }

    public int[] lowestAverage(int[][] array){

        ArrayList<Double> averageCollection = new ArrayList<>();

        for(int i=0; i<array.length;i++){
            double sum=0;
            for(int j = 0 ; j<array[i].length;j++){
                sum+=array[i][j];
            }
            averageCollection.add(sum/array[i].length);
        }
        return array[averageCollection.indexOf(Collections.min(averageCollection))];
    }

}