/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.File;
import java.io.IOException;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        linter();
    }

    public static void linter() {

        try {

            File myPath = new File("./app/src/main/resources/gates.js");
            Scanner lineReader = new Scanner(myPath);
            int counter = 1;
            while (lineReader.hasNextLine()) {
                String line = lineReader.nextLine();
                if (!line.endsWith(";") && !line.endsWith("}") && !line.endsWith("{") && !line.contains("else") && !line.contains("if") && !line.isEmpty()) {

                    String printLine = "Line " + counter + " : Missing semicolon.";

                    System.out.println(printLine);
                }
                counter++;
            }
            lineReader.close();
        } catch (IOException ioException) {
            System.out.println(ioException.getMessage());
        }
    }
}
