/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;

class MainTest {

        @Test void someLibraryMethodReturnTrue(){
        Main classUnderTest = new Main();
        }
        @Test void constructorRestaurant() {
            Restaurant test = new Restaurant("kfc",4,10);
        }
}
